<!DOCTYPE html>
<html>
	<head>
		<title>Nonogram</title>
		<link rel="stylesheet" type="text/css" href="style.css" />
		<link rel='shortcut icon' type='image/ico' href='favicon.ico' />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
		<script src="main.js"></script>
	</head>
	<body>
		